packages:
  - '**'
  - '!dist'
  - '!**/dist/**'
allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  esbuild: false
  msw: false
  sharp: false
  workerd: true
minimumReleaseAgeExclude:
  - '@umami/react-zen'
